### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by hicane0** [yechentide/DSTServerManager#1]
最近也找了很多的开服脚本，发现不尽人意的地方很多，个人感觉 dstserver的界面管理+go.sh的功能组合到一起比较合适，目前go.sh和dstserver发现的问题
先说go.sh
1.这个就是针对Ubantu系统写得，没有增加对Centos的支持，里面在装环境的时候默认的是装不了，要把代码对应部分改成Centos的支持库
2.force_install_dir 命令要在login anonymous之前，这个不知道是Steamcmd改的还是以前这样，但是我手动走流程的时候，是这样提示的，但是go.sh的脚本是反过来的（我看网上大多教程都是反过来的，不知道这个有没有影响，反正我第一次跑通的时候是要调整顺序才可以）
3.在某一个版本以后，要想跑通是要把libcurl.so.4重链接的，但是go.sh有这行代码但是不知道为什么给注释掉了（这也是现在go.sh跑不通的绝大多数人遇到的问题）
4.接上条，go.sh注释的地方你单纯的解开是不行，他的跟路径文件夹是带引号的Don't Starve Together Dedicated Server这个名字，不知道出于什么考量，单引号+空格，太容易出问题了，在执行某些命令的时候，最好是全局替换一下
5.解决了以上问题，go.sh 洞穴跑的通，但是世界一直有问题，暂时没有找到问题原因

dstserver.sh
1.这个脚本的mod管理我就没跑通过
2.启动服务器的逻辑不是很好，个人感觉go.sh的逻辑比较好，从存档槽中启动, dst的逻辑是在上次启动的服务器和新服务器之间选择

他俩各自的优点，晚点再说

**Comment by yechentide** [comment]
哇，多谢你的建议！
目前脚本只是提供了最最基础的功能，有人能来提建议太好了hh

## go.sh

1. 我写的脚本目前也只是在ubuntu上面测试过，虽然我参考了别人的脚本，也增加了CentOS所需的依赖，但仍然没有测试过。等一个用Redhat系列的小白鼠出现hh
2. force_install_dir的那个warning我也注意到了，但是我用的时候都可以正常安装使用，晚点我试试看消除warning
3. libcurl.so.4这个问题我第一次听说。我以前一直用的dstserver.sh，go.sh不熟悉，有时间我去试试看。
4. 简单来说就是把go.sh的功能给分解重构就是了，我半年前好像稍微看过，感觉dstserver.sh更好
5. go.sh不大清楚，另外听说go.sh开的服，齿轮怪会很少...

## dstserver.sh

1. 我用了很久了啊，mod管理感觉没问题啊
2. 这个我没注意，不过我写的好像就是从存档里面选一个启动

## 其他的

我写的脚本主要还是我自己在用hh
发到贴吧没人理，不过我去gitee上面看了下，开服脚本还是有一些的。
我还会继续添加功能，我自己用着的时候发现应该支持单/多服务器开单/多cluster，等等。
不过我最近忙可能要等明年一月底才能更新了

感谢你的建议，我有空继续修改脚本的时候，我会注意下的。
到时候go.sh和dstserver.sh的代码我再看一下hh

**Comment by yechentide** [comment]
v1.3.0的ToDo:
- [x] Ubuntu和CentOS的依赖库测试

**Comment by yechentide** [comment]
版本1.4之后的脚本你可以试试哦～
