### ISSUE TITLE
您好，请问如何进行世界的删除操作呢？

### ISSUE THREAD

**Issue by JefferyCheng97** [yechentide/DSTServerManager#2]
是直接在KLEI文件夹下面删除世界吗？

**Comment by yechentide** [comment]
删除功能还没写抱歉了hh。。。
世界存档保存在`~/Klei/worlds`里面，直接在那边删除就行。
另外，哪个文件夹放了什么东西，我在[这个文档](https://github.com/yechentide/DSTServerManager/blob/main/docs/%E7%BB%93%E6%9E%84.sh)里面说明了哦～你可以看看

**Comment by JefferyCheng97** [comment]
> 

好的，谢谢

**Comment by yechentide** [comment]
v1.2.3开始支持删除存档了
https://github.com/yechentide/DSTServerManager/blob/c37354270d065d7d0611762ddcfce9fce5c335c2/scripts/cluster.sh#L309-L331
