### ISSUE TITLE
在存档配置管理&mod添加方面遇到的问题

### ISSUE THREAD

**Issue by Mephistopher** [yechentide/DSTServerManager#21]
您好，我刚开始试着用您的脚本搭建一个饥荒的服务器，在存档配置管理&mod添加方面遇到了问题
1. 设置存档配置时（新建存档时或者对已有存档进行修改时）除了yes/no和配置选项内容之外，所有的提示性文字都是黑色的，只能看见空行，复制到其它地方的确是有文字的。

2. 下载完mod后试着向已有存档添加mod时会报如下错误：

> lua: /home/ubuntu/DSTServerManager/scripts/mod_manager.lua:85: attempt to concatenate a nil value (global 'modinfo_cache_dir')
> stack traceback:
>         	/home/ubuntu/DSTServerManager/scripts/mod_manager.lua:85: in function 'generate_installed_mods_table'
>         	/home/ubuntu/DSTServerManager/scripts/mod_manager.lua:246: in function 'add_new_mods'
>         	/home/ubuntu/DSTServerManager/scripts/mod_manager.lua:307: in main chunk
>        	[C]: in ?

服务器是腾讯云租用的，系统是Ubuntu Server 20.04 LTS 64bit，脚本版本是v1.4.2

**Comment by yechentide** [comment]
感谢使用～
第一个问题：我的终端被我改的花里胡俏了，所以可能我这显示的颜色，有些终端里不能很好的显示。你可以贴几张图吗？随便贴哪，给我个链接就好。
第二个问题：1.4.1.2 --> 1.4.2时，我大幅修改了变量命名，这个地方漏改了所以会报错，抱歉了hh
版本[1.4.2.1](https://github.com/yechentide/DSTServerManager/commit/10767f3245c814a4e282f94c125f3964838757a9)已经修复

**Comment by yechentide** [comment]
另外这种大幅度的修改以后应该没有了,请放心。(滑稽)

**Comment by yechentide** [comment]
如果你有更好的配色推荐的话，也可以提出来～

**Comment by Mephistopher** [comment]
> 

我截了几张终端显示的图分享在阿里云盘，感谢这么快的修复，新年快乐

> https://www.aliyundrive.com/s/YgJedagVZR4

**Comment by yechentide** [comment]
[v1.4.2.2](https://github.com/yechentide/DSTServerManager/commit/e79c080731a84fd6abef176463a22a0ac941c6c9)已修复输出问题。
原因还是变量名emmm
希望没有bug了, 祝你新年玩的愉快～
