### ISSUE TITLE
在向新存档添加mod时遇到的问题

### ISSUE THREAD

**Issue by Mephistopher** [yechentide/DSTServerManager#22]
您好，我在试图添加mod时给出了如下报错，因为不知道具体是哪边的问题所以我向两方都做出了反馈

> lua: /home/ubuntu/DSTServerManager/.cache/modinfo/2328604820.lua:101: invalid escape sequence near '"Deal 1.5 times damage to plant-type mobs\('
> stack traceback:
> 	[C]: in function 'dofile'
> 	/home/ubuntu/DSTServerManager/scripts/mod_manager.lua:85: in function 'generate_installed_mods_table'
> 	/home/ubuntu/DSTServerManager/scripts/mod_manager.lua:246: in function 'add_new_mods'
> 	/home/ubuntu/DSTServerManager/scripts/mod_manager.lua:307: in main chunk
> 	[C]: in ?

其中2328604820对应的mod是

> https://steamcommunity.com/sharedfiles/filedetails/?id=2328604820

这个mod有一个设置是“对植物造成1.5倍伤害”

**Comment by yechentide** [comment]
我试着用lua语言直接读取modinfo.lua文件, 读取失败。
所以可能是mod作者多写了两个字符
> 第101行: Deal 1.5 times damage to plant-type mobs\\(eg. eyeplants\\)
> 第301行: 对植物造成1.5倍伤害\\(如眼球草\\)

`\(`改成`(`, `\)`改成`)`

不过说不定是mod作者有其他需求加的这个
毕竟我不了解mod制作

你可以自己修改下文件来使脚本正常工作
修改`~/DSTServerManager/.cache/modinfo/2328604820.lua`

**Comment by yechentide** [comment]
ToDo:

- [ ] mod删除功能
- [ ] 检测modinfo.lua是否可以读取
