### ISSUE TITLE
添加的mod不起效

### ISSUE THREAD

**Issue by Mephistopher** [yechentide/DSTServerManager#23]
如题，今天开新档添加了几个mod进游戏发现没起作用，用T键看不到模组物品，血条显示类也没有显示，但是用电脑直接创建世界并启用相同mod发现是可以正常工作的_(:з)∠)_

**Comment by yechentide** [comment]
你能帮忙看看几个文件/文件夹嘛？
1. `~/Server/mods/dedicated_server_mods_setup.lua`这个文件里面写了啥
2. `~/Server/mods`文件夹里面`workshop`开头的文件夹有哪些
3. `~/Server/ugc_mods/content/322330`文件夹里面有哪些东西
4. `~/DSTServerManager/.cache/modinfo`文件夹里面有哪些东西
5. 确认下你存档里所有的`modoverrides.lua`, mod的ID有没有在里面
6. 不起作用的mod的ID也说一下

**Comment by yechentide** [comment]
我新建了个Bug反馈QQ群927694504
你可以加一下方便发图～

**Comment by Mephistopher** [comment]
好，只是这几天年关事情比较多，等有时间我会第一时间反馈

**Comment by yechentide** [comment]
版本1.4.2.5已修复
[commit: 34de681e557a4ec33cf158783deb7e131445ac60](https://github.com/yechentide/DSTServerManager/commit/34de681e557a4ec33cf158783deb7e131445ac60)

原因是更新服务端时, `~/Server/mods/dedicated_server_mods_setup.lua`文件会被重置
