### ISSUE TITLE
无法正常启动

### ISSUE THREAD

**Issue by CNLouisLiu** [yechentide/DSTServerManager#24]
====================================================================================================================================================================================================================================================
 DST Dedicated Server Manager v1.4.3.1
 Github仓库: https://github.com/yechentide/DSTServerManager
 Gitee仓库: https://gitee.com/yechentide/DSTServerManager
 全部代码上传到以上仓库里了, 有兴趣的伙伴可以来一起改善功能！
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[TIP] 如果服务器列表里不显示服务器, 请检查端口和防火墙&云服的安全组设置!
[TIP] 如果你启动游戏时看到有更新的话, 服务端这边也需要更新! 服务端管理界面可以更新服务端。
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

>>>>>> >>>>>> 主面板 <<<<<< <<<<<<
/home/dts/DSTManager.sh:行616: running_cluster_list: 只读变量

对应的shell代码declare -r -a running_cluster_list=$(generate_list_from_tmux -s | tr '\n' ' ')

**Comment by yechentide** [comment]
谢谢反馈
shell的变量scope好迷。。。

**Comment by yechentide** [comment]
`running_cluster_list`这个变量, 我只在这个函数里使用。
按理说不应该报错"只读变量"的啊。其他人也没问题。
你试试去掉`-r`, 也就是把`declare -r -a running_cluster_list`改成`declare -a running_cluster_list`。
还有你的Bash版本能说一下吗

**Comment by CNLouisLiu** [comment]
系统问题 我换了Centos这个脚本不支持..

**Comment by CNLouisLiu** [comment]
> `running_cluster_list`我把这个函数里的变量里用了。按理说 我不应该报错在改成“Bash的其他变量”的 啊 。吗`-r``declare -r -a running_cluster_list``declare -a running_cluster_list`

系统问题 Centos这个脚本不支持.. 我换了ubuntu运行正常.

**Comment by yechentide** [comment]
你的是CentOS几？我用docker试试看

**Comment by yechentide** [comment]
版本[1.4.3.3](https://github.com/yechentide/DSTServerManager/commit/9c093049b95ed2431b7b1e9a59268bcd9138b035)已经修复
