### ISSUE TITLE
在 Ubuntu22 的系统下 lib32gcc1 无法安装

### ISSUE THREAD

**Issue by StringKe** [yechentide/DSTServerManager#30]
https://github.com/PolarNightCLI/DSTServerManager/blob/f97392c24614b39c8d325cddfbb7264c0ea18670/bin/environment/install_dependencies#L43

脚本在检测 lib32gcc1 apt源中是没有这个包的

**Comment by yechentide** [comment]
`lib32gcc1`被更名为`lig32gcc-s1`
版本[v1.5.6](https://github.com/PolarNightCLI/DSTServerManager/releases/tag/v1.5.6)已经修好了:D

**Comment by KanlentB** [comment]
> `lib32gcc1`被更名为`lig32gcc-s1` 版本[v1.5.6](https://github.com/PolarNightCLI/DSTServerManager/releases/tag/v1.5.6)已经修好了:D

server上的旧东西在老版本的ubuntu上更好用点，当时用的ubuntu18.04，出现了相反的问题，找不到lib32gcc-s1

**Comment by yechentide** [comment]
看来需要更确认系统版本再决定依赖库啊，有空了我改改

**Comment by yechentide** [comment]
看来需要确认系统版本再决定依赖库啊，有空了我改改

**Comment by yechentide** [comment]
[稍微改了一下](https://github.com/PNCommand/DSTServerManager/commit/c42ffb013cae3bd81941aede74c6f77b6d50d1cb#diff-17d7ab3cc9e928d648f8645e5caae1a1de55a02d1374f7f3b136d4220976f218L40-L46)，在Docker的Ubuntu18.04测试了下没问题。
其他版本有问题再改吧hh
